name: Tests Artifact
on: push
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Mon application" > my_app.txt
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          # Artifact name
          name: App_To_Deploy
          # A file, directory or wildcard pattern that describes what to upload
          path: my_app.txt
    
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.1.1
        with:
          # Artifact name
          name: App_To_Deploy
      - run: |
          ls
          cat my_app.txt
          
