name: Tests Cache
on: push
jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
      - run: |
          mkdir dep
          echo "Mon application" > ./dep/my_app.txt
          - name: Cache
            uses: actions/cache@v3.3.2
            with:
              # A list of files, directories, and wildcard patterns to cache and restore
              path: dep/
              # An explicit key for restoring and saving the cache
              key: mon_cache
      
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: |
          ls
          cat my_app.txt
          
