name: Tests srects and Variables
on: push
jobs: 
  display_values:
    runs-on: ubuntu-latest
    outputs:
      MON_RETOUR: ${{ steps.step-return.outputs.result }}
    steps:
      - run: |
          echo "${{ secrets.DATABASE_SECRET }}"
          echo "${{ vars.VERSION }}"
      - name: GitHub Script
        uses: actions/github-script@v7.0.1
        id: step-return
        with:
          # The script to run
          script: return "Mon retour"; 
    
  display_return:
    needs: display_values
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ needs.display_values.outputs.MON_RETOUR }}"
          
